"use server";

import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth/require";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { getCurrentWorkspace } from "@/lib/workspace";

export type Document = {
  id: string;
  workspace_id: string;
  name: string;
  description: string;
  file_url: string;
  storage_path: string;
  mime_type: string;
  size: number;
  uploaded_by: string | null;
  source_agent: string | null;
  tags: string[];
  created_at: string;
};

type Result<T = void> = { ok: true; data?: T } | { ok: false; error: string };

/** List all documents for the active workspace. */
export async function listDocuments(): Promise<Document[]> {
  await requireUser();
  const ctx = await getCurrentWorkspace();
  if (!ctx) return [];

  const admin = createSupabaseAdminClient();
  const { data } = await admin
    .from("documents")
    .select("*")
    .eq("workspace_id", ctx.workspace.id)
    .order("created_at", { ascending: false })
    .limit(100);

  return (data ?? []) as Document[];
}

/** Upload a document to the vault. */
export async function uploadDocument(formData: FormData): Promise<Result<{ id: string }>> {
  const user = await requireUser();
  const ctx = await getCurrentWorkspace();
  if (!ctx) return { ok: false, error: "No workspace found." };

  const file = formData.get("file") as File | null;
  if (!file || file.size === 0) return { ok: false, error: "No file provided." };
  if (file.size > 10 * 1024 * 1024) return { ok: false, error: "File exceeds 10 MB limit." };

  const description = (formData.get("description") as string) ?? "";
  const tags = ((formData.get("tags") as string) ?? "").split(",").map(t => t.trim()).filter(Boolean);

  const admin = createSupabaseAdminClient();
  const docId = crypto.randomUUID();
  const storagePath = `${ctx.workspace.id}/vault/${docId}/${file.name}`;

  // Upload to Supabase Storage
  const buffer = Buffer.from(await file.arrayBuffer());
  const { error: uploadErr } = await admin.storage
    .from("chat-attachments")
    .upload(storagePath, buffer, { contentType: file.type, upsert: true });

  if (uploadErr) return { ok: false, error: `Upload failed: ${uploadErr.message}` };

  const { data: urlData } = admin.storage
    .from("chat-attachments")
    .getPublicUrl(storagePath);

  // Insert DB row
  const { data, error } = await admin
    .from("documents")
    .insert({
      id: docId,
      workspace_id: ctx.workspace.id,
      name: file.name,
      description,
      file_url: urlData.publicUrl,
      storage_path: storagePath,
      mime_type: file.type || "application/octet-stream",
      size: file.size,
      uploaded_by: user.id,
      tags,
    })
    .select("id")
    .single();

  if (error || !data) return { ok: false, error: error?.message ?? "Insert failed." };

  revalidatePath("/documents");
  return { ok: true, data: { id: data.id } };
}

/** Delete a document from vault + storage. */
export async function deleteDocument(id: string): Promise<Result> {
  await requireUser();
  const ctx = await getCurrentWorkspace();
  if (!ctx) return { ok: false, error: "No workspace found." };

  const admin = createSupabaseAdminClient();

  // Get storage path before deleting
  const { data: doc } = await admin
    .from("documents")
    .select("storage_path")
    .eq("id", id)
    .eq("workspace_id", ctx.workspace.id)
    .maybeSingle();

  if (!doc) return { ok: false, error: "Document not found." };

  // Delete from storage (non-fatal)
  await admin.storage.from("chat-attachments").remove([doc.storage_path]).catch(() => {});

  // Delete DB row
  const { error } = await admin
    .from("documents")
    .delete()
    .eq("id", id)
    .eq("workspace_id", ctx.workspace.id);

  if (error) return { ok: false, error: error.message };
  revalidatePath("/documents");
  return { ok: true };
}

/** Save an agent-generated output to the vault. Called from the chat route. */
export async function saveAgentOutput(opts: {
  workspaceId: string;
  agentRole: string;
  messageId: string;
  name: string;
  content: string;
  mimeType?: string;
}): Promise<void> {
  try {
    const admin = createSupabaseAdminClient();
    const docId = crypto.randomUUID();
    const storagePath = `${opts.workspaceId}/vault/${docId}/${opts.name}`;

    const buffer = Buffer.from(opts.content, "utf-8");
    await admin.storage
      .from("chat-attachments")
      .upload(storagePath, buffer, {
        contentType: opts.mimeType ?? "text/markdown",
        upsert: true,
      });

    const { data: urlData } = admin.storage
      .from("chat-attachments")
      .getPublicUrl(storagePath);

    await admin.from("documents").insert({
      id: docId,
      workspace_id: opts.workspaceId,
      name: opts.name,
      description: `Generated by ${opts.agentRole.toUpperCase()}`,
      file_url: urlData.publicUrl,
      storage_path: storagePath,
      mime_type: opts.mimeType ?? "text/markdown",
      size: buffer.length,
      source_agent: opts.agentRole,
      source_message_id: opts.messageId,
    });
  } catch {
    // Non-fatal — vault save failure shouldn't break the chat
  }
}
