-- =========================================================
-- Migration 0011 · Document Vault
-- =========================================================
-- WHAT: Shared workspace-wide document library.
--   Files uploaded by users or generated by AI agents are
--   stored here for cross-agent access. Any agent can
--   reference any document in the vault.
--
-- ROLLBACK: DROP TABLE public.documents;
-- =========================================================

create table if not exists public.documents (
  id                uuid        primary key default gen_random_uuid(),
  workspace_id      uuid        not null references public.workspaces(id) on delete cascade,
  name              text        not null,
  description       text        not null default '',
  file_url          text        not null default '',
  storage_path      text        not null,
  mime_type         text        not null,
  size              integer     not null,
  uploaded_by       uuid        references public.profiles(id),
  source_agent      text,                     -- which agent generated this (null = user upload)
  source_message_id uuid,                     -- message that generated this document
  tags              text[]      not null default '{}',
  created_at        timestamptz not null default now()
);

create index if not exists documents_ws_idx
  on public.documents (workspace_id, created_at desc);

alter table public.documents enable row level security;

drop policy if exists documents_owner_all on public.documents;
create policy documents_owner_all on public.documents
  for all using (public.is_owner(workspace_id))
  with check (public.is_owner(workspace_id));

-- Self-test
do $$
begin
  if not exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'documents'
  ) then
    raise exception 'Migration 0011 FAILED — documents table missing';
  end if;
  raise notice 'Migration 0011 PASSED — document vault ready.';
end $$;
